export function formatFrameAsXyz(
  frame,
  frameIndex,
  totalFrames,
  energyDecimals,
) {
  const atomCount = frame?.atoms?.length ?? 0;
  const energy =
    frame?.energy_hartree == null
      ? "N/A"
      : frame.energy_hartree.toFixed(energyDecimals);
  const header = `${atomCount}\nFrame ${frameIndex + 1}/${totalFrames}; Energy(Hartree)=${energy}\n`;
  const atomLines = (frame?.atoms || [])
    .map(
      (atom) =>
        `${atom.element} ${atom.x.toFixed(10)} ${atom.y.toFixed(10)} ${atom.z.toFixed(10)}`,
    )
    .join("\n");
  return atomLines ? `${header}${atomLines}\n` : header;
}

export function formatFrameAsGjf(
  frame,
  frameIndex,
  totalFrames,
  charge,
  multiplicity,
) {
  const ch = Number.isInteger(charge) ? charge : 0;
  const mult = Number.isInteger(multiplicity) ? multiplicity : 1;
  const title = `Generated from frame ${frameIndex + 1}/${totalFrames}`;
  const route = "#P Generated by molvis";
  const atomLines = (frame?.atoms || [])
    .map(
      (atom) =>
        `${atom.element} ${atom.x.toFixed(10)} ${atom.y.toFixed(10)} ${atom.z.toFixed(10)}`,
    )
    .join("\n");
  return `${route}\n\n${title}\n\n${ch} ${mult}\n${atomLines}\n`;
}

export function updateTextPanelToggleLabel(state, elements) {
  const { exportXyzBtn, exportGjfBtn, xyzTextPanel, textPanelTitle } = elements;
  if (!exportXyzBtn || !exportGjfBtn || !xyzTextPanel) return;
  const shown = !xyzTextPanel.classList.contains("hidden");
  const xyzActive = shown && state.textExportMode === "xyz";
  const gjfActive = shown && state.textExportMode === "gjf";
  exportXyzBtn.textContent = xyzActive ? "Hide XYZ Text" : "Show XYZ Text";
  exportGjfBtn.textContent = gjfActive ? "Hide GJF Text" : "Show GJF Text";
  if (textPanelTitle) {
    textPanelTitle.textContent =
      state.textExportMode === "gjf"
        ? "Current Frame GJF"
        : "Current Frame XYZ";
  }
}

export function buildCurrentText(state, energyDecimals) {
  const frame = state.frames[state.currentIndex];
  return state.textExportMode === "gjf"
    ? formatFrameAsGjf(
        frame,
        state.currentIndex,
        state.frames.length,
        state.charge,
        state.multiplicity,
      )
    : formatFrameAsXyz(
        frame,
        state.currentIndex,
        state.frames.length,
        energyDecimals,
      );
}

export function showCurrentFrameText(
  state,
  elements,
  setStatus,
  energyDecimals,
) {
  const { xyzTextPanel, xyzTextOutput } = elements;
  if (!state.frames.length) {
    setStatus("No frame available to export.");
    return;
  }
  xyzTextOutput.value = buildCurrentText(state, energyDecimals);
  xyzTextPanel.classList.remove("hidden");
  updateTextPanelToggleLabel(state, elements);
  xyzTextOutput.focus();
  xyzTextOutput.select();
  const kind = state.textExportMode === "gjf" ? "GJF" : "XYZ";
  setStatus(`${kind} text ready for frame ${state.currentIndex + 1}.`);
}

export function toggleCurrentFrameText(
  mode,
  state,
  elements,
  setStatus,
  energyDecimals,
) {
  const { xyzTextPanel, xyzTextOutput } = elements;
  if (!xyzTextPanel || !xyzTextOutput) return;
  const shown = !xyzTextPanel.classList.contains("hidden");
  if (shown && state.textExportMode === mode) {
    xyzTextPanel.classList.add("hidden");
    updateTextPanelToggleLabel(state, elements);
    setStatus("Text panel hidden.");
    return;
  }
  state.textExportMode = mode;
  showCurrentFrameText(state, elements, setStatus, energyDecimals);
}

export function syncVisibleText(state, elements, energyDecimals) {
  const { xyzTextPanel, xyzTextOutput } = elements;
  if (!xyzTextPanel || !xyzTextOutput) return;
  if (xyzTextPanel.classList.contains("hidden")) return;
  if (!state.frames.length) {
    xyzTextOutput.value = "";
    return;
  }
  xyzTextOutput.value = buildCurrentText(state, energyDecimals);
}

export async function copyCurrentText(state, elements, setStatus) {
  const { xyzTextOutput } = elements;
  if (!xyzTextOutput) return;
  const text = xyzTextOutput.value;
  const kind = state.textExportMode === "gjf" ? "GJF" : "XYZ";
  if (!text) {
    setStatus(`No ${kind} text to copy.`);
    return;
  }
  try {
    await navigator.clipboard.writeText(text);
    setStatus(`${kind} text copied to clipboard.`);
  } catch {
    xyzTextOutput.focus();
    xyzTextOutput.select();
    setStatus("Auto-copy blocked; text selected, press Ctrl+C.");
  }
}
